#pragma once

struct weapon_info_t {
	char		  u0[4];
	char*         weapon_name;
	char		  u1[12];
	int		      weapon_max_clip;
	char		  u2[12];
	int		      weapon_max_reserved_ammo;
	char		  u3[4];
	char*         weapon_model_path;
	char*         weapon_model_path_alt;
	char*         weapon_dropped_model_path;
	char*         weapon_default_clip;
	char		  u4[68];
	char*         weapon_bullet_type;
	char	  	  u5[4];
	char*         weapon_hud_name;
	char*         weapon_name_alt;
	char		  u6[56];
	int		      weapon_type;
	int		      weapon_type_alt;
	int		      weapon_price;
	int		      weapon_reward;
	char*         weapon_type_name;
	float		  weapon_unknown_float;
	char		  u7[12];
	unsigned char weapon_full_auto;
	char		  u8[3];
	int		      weapon_damage;
	float		  weapon_armor_ratio;
	int		      weapon_bullets;
	float		  weapon_penetration;
	char		  u9[8];
	float		  weapon_range;
	float		  weapon_range_mod;
	float		  weapon_throw_velocity;
	char		  u10[12];
	unsigned char weapon_has_silencer;
	char		  u11[15];
	float		  weapon_max_speed;
	float		  weapon_max_speed_alt;
	float		  weapon_attack_move_factor;
	float		  weapon_spread;
	float		  weapon_spread_alt;
	float		  weapon_inaccuracy_crouch;
	float		  weapon_inaccuracy_crouch_alt;
	float		  weapon_inaccuracy_stand;
	float		  weapon_inaccuracy_stand_alt;
	float		  weapon_inaccuracy_jump;
	float		  weapon_inaccuracy_jump_alt;
	char		  u12[40];
	int		      weapon_recoil_seed;
	char		  u13[104];
	char*         weapon_traces_type;
};