#pragma once

struct weapon_info_t {
	char		  u0[4];
	char*         m_weapon_name;
	char		  u1[12];
	int		      m_weapon_max_clip;
	char		  u2[12];
	int		      m_weapon_max_reserved_ammo;
	char		  u3[4];
	char*         m_weapon_model_path;
	char*         m_weapon_model_path_alt;
	char*         m_weapon_dropped_model_path;
	char*         m_weapon_default_clip;
	char		  u4[68];
	char*         m_weapon_bullet_type;
	char	  	  u5[4];
	char*         m_weapon_hud_name;
	char*         m_weapon_name_alt;
	char		  u6[56];
	int		      m_weapon_type;
	int		      m_weapon_type_alt;
	int		      m_weapon_price;
	int		      m_weapon_reward;
	char*         m_weapon_type_name;
	float		  m_weapon_unknown_float;
	char		  u7[12];
	unsigned char m_weapon_full_auto;
	char		  u8[3];
	int		      m_weapon_damage;
	float		  m_weapon_armor_ratio;
	int		      m_weapon_bullets;
	float		  m_weapon_penetration;
	char		  u9[8];
	float		  m_weapon_range;
	float		  m_weapon_range_mod;
	float		  m_weapon_throw_velocity;
	char		  u10[12];
	unsigned char m_weapon_has_silencer;
	char		  u11[15];
	float		  m_weapon_max_speed;
	float		  m_weapon_max_speed_alt;
	float		  m_weapon_attack_move_factor;
	float		  m_weapon_spread;
	float		  m_weapon_spread_alt;
	float		  m_weapon_inaccuracy_crouch;
	float		  m_weapon_inaccuracy_crouch_alt;
	float		  m_weapon_inaccuracy_stand;
	float		  m_weapon_inaccuracy_stand_alt;
	float		  m_weapon_inaccuracy_jump;
	float		  m_weapon_inaccuracy_jump_alt;
	char		  u12[40];
	int		      m_weapon_recoil_seed;
	char		  u13[104];
	char*         m_weapon_traces_type;
};